name: NodeJS AWS EC2 Tutorial

on:
    push:
        branches:
            - master
jobs:
    deployment:
        name: Deploy master branch to EC2
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout master branch
              uses: actions/checkout@v3
      
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20.5.x'

            - name: Connect to Server
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: '${{ secrets.EC2_SSH_KEY }}'
                REMOTE_HOST: '${{ secrets.HOST_DNS }}'
                REMOTE_USER: '${{ secrets.USERNAME }}'
                TARGET: 'node-app'
      
            - name: Executing Remote SSH Commands
              uses: appleboy/ssh-action@master
              env:
                APP_ENV: '${{ secrets.APP_ENV }}'
              with:
                host: ${{ secrets.HOST_DNS }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  sudo apt-get -y update
                  cd node-app
                  git pull origin master
                  npm install yarn pm2 -g
                  rm -f .env
                  touch .env
                  echo APP_ENV='${{ secrets.APP_ENV }}' >> .env
                  cat .env
                  yarn install
                  pm2 start index.js --name node-app
